apiVersion: v1

kind: Pod

metadata:
  name: db-pod
  labels:
    app: db
    tier: db-tier
    type: back-end
    costcenter: India
    location: Pune

spec:
  containers:
    - name: postgres-container
      image: postgres
