apiVersion: apps/v1

kind: Deployment

metadata:
  name: nginx-server-deployment
  labels:
    app: nginx-server
    type: front-end

spec:
  template:
    metadata:
      name: nginx-server-pod
      labels:
        app: nginx-server

    spec:
      containers:
        - name: nginx-container
          image: nginx

  replicas: 3
  selector:
    matchLabels:
      app: nginx-server
